### ISSUE TITLE
401 errors

### ISSUE THREAD

**Issue by TomAFrench** [mpepping/github-actions#6]
I'm getting 401 errors when using this action in [this flow](https://github.com/TomAFrench/liquidity-burner/blob/master/.github/workflows/dockerhubmetadata.yml). I'm using the same credentials in [this action](https://github.com/TomAFrench/liquidity-burner/blob/master/.github/workflows/dockerimage.yml) successfully so I'm not sure why it's failing.

Does anyone else have issues using this action?

**Comment by softprops** [comment]
Just noticed this as well

**Comment by mpepping** [comment]
Thanks for reporting! Noticed this for my own builds as well 😞 
Seems that updating metadata via personal access tokens is disabled on Docker Hub a short while back: https://github.com/docker/hub-feedback/issues/1927 

For now, let's disable this build action and see how things develop on Docker Hub.
